name: Atualizador Automático do Bolão

on:
  schedule:
    - cron: '0 */2 * * *' 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  atualiza-html:
    runs-on: ubuntu-latest
    steps:
      - name: Baixa o repositório
        uses: actions/checkout@v4

      - name: Prepara o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instala a biblioteca de requisições
        run: pip install requests

      - name: Roda o script de atualização
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: python atualiza_placar.py

      - name: Salva as alterações no GitHub (Commit)
        run: |
          git config --global user.name 'Robô do Bolão'
          git config --global user.email 'action@github.com'
          git add .
          # O "|| exit 0" garante que, se não houver mudanças, ele não dá erro
          git commit -m "⚽ Atualização automática de placares" || exit 0
          git push
